language: python

os: linux
dist: trusty
group: edge

python:
    - "2.7"
    - "3.6.5"

env:
    matrix:
        - TESTENV=docs
        - TESTENV=code
        - TESTENV=pylint

before_install:
    - pip install numpy
    - sudo chmod +x scripts/travis/includeMAC2.sh
    - sudo chmod +x scripts/travis/includeSamTools.sh
    - ./scripts/travis/includeMAC2.sh

# command to install dependencies
install:
    - pip install .
    - pip install -r requirements.txt
    - if [[ "$TESTENV" == "docs" ]]; then pip install sphinx;fi
    - if [[ "$TESTENV" == "pylint" ]]; then pip install pylint;fi

    - if [[ "$TESTENV" == "code" ]]; then ./scripts/travis/includeSamTools.sh; fi

# command to run tests
script:
    - if [[ "$TESTENV" == "code" ]]; then pytest -m "not underdeverlopment"; fi
    - if [[ "$TESTENV" == "docs" ]]; then ./scripts/travis/docs_harness.sh; fi
    - if [[ "$TESTENV" == "pylint" ]]; then ./scripts/travis/pylint_harness.sh; fi
